### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by bengalspice** [AnnaRey/intro-data-capstone-biodiversity#1]
- For the Species dataset, it would have made the presentation more visually appealing if you had listed the species out in a table with the numbers of each species, as well as making a table of the different status of each species with the corresponding numbers.

- Make sure to proofread presentations and write statements as complete sentences so the slides are easy to understand.

- I liked that you included images pivot tables with protection status and percentages, as well as a table of the total number of species in each category.

- It would have been nice to show the pivot tables for each species comparison as part of data visualization.

- There wasn't a clear Recommendation for conservation. 

Overall, it's clear that you performed the coding for this capstone correctly. It would have been nice to see more data manipulation in the presentation, as well as playing around with visualization. Don't be afraid to play around with the bar graphs to change the colors to correspond with slideshow themes. I hope you enjoyed the Intensive and will play around more with the data and visualization to discover new trends. Take care!

**Comment by AnnaRey** [comment]
Thank you for the review! I have definitely enjoyed the course.
